title: [Project 1: <font style="color : darkorange">Analysis of Customer Retention</font>]
#logo: /img/headshot_circle.jpg
description: [Senior Data Analyst]
#show_downloads: true
theme: jekyll-theme-slate
